name: '이슈 생성'
description: 'Repo에 이슈를 생성하며, 생성된 이슈는 Jira와 연동됩니다.'
labels: [feat]
title: '이슈 이름을 작성해주세요'
body:
  - type: dropdown
    id: issueparser_issueType
    attributes:
      label: '이슈 타입 (Issue Type)'
      description: '생성할 이슈의 타입을 선택해주세요'
      options:
        - 작업
        - 버그
        - 스토리
      default: 0
    validations:
      required: true

  - type: input
    id: issueparser_parentKey
    attributes:
      label: '상위 작업 (Parent Issue)'
      placeholder: 'WL7-123'
      description: '상위 작업의 Ticket Number를 WL7-XXX 형식으로 기입해주세요 (선택사항) - 주의: 버그 타입은 상위 항목을 입력하지 마세요'
    validations:
      required: false

  - type: input
    id: issueparser_description
    attributes:
      label: '상세 내용 (Description)'
      description: '이슈에 대해서 간략히 설명해주세요'
    validations:
      required: true
      
  - type: textarea
    id: issueparser_tasks
    attributes:
      label: '체크리스트 (Tasks)'
      description: '해당 이슈에 대해 필요한 작업목록을 작성해주세요'
      value: |
        - [ ] Task 1
    validations:
      required: true
